### ISSUE TITLE
issue: embedded mongodb throws socket exception

### ISSUE THREAD

**Issue by ezelsu** [srdc/onfhir#7]
# Issue report

**Expected Behavior** 

Should have written resources successfully

**Steps to Reproduce the Problem**

  1. make embedded=true for mongodb in config file
  1. make host = ["localhost:27018"] for mongodb in config file
  1. try to write resources to repository

**Logs**

```
[mongod output] : Permission denied
[mongod output] 2020-09-21T11:40:34.228+0300 E STORAGE  [WTCheckpointThread] WiredTiger error (13) [1600677634:227954][16124:140717079221488], file:WiredTiger.wt, WT_SESSION.checkpoint: __wt_turtle_update, 397: WiredTiger.turtle: fatal turtle file update error: Permission denied Raw: [1600677634:227954][16124:140717079221488], file:WiredTiger.wt, WT_SESSION.checkpoint: __wt_turtle_update, 397: WiredTiger.turtle: fatal turtle file update error: Permission denied
[mongod output] 2020-09-21T11:40:34.228+0300 E STORAGE  [WTCheckpointThread] WiredTiger error (-31804) [1600677634:227954][16124:140717079221488], file:WiredTiger.wt, WT_SESSION.checkpoint: __wt_panic, 523: the process must exit and restart: WT_PANIC: WiredTiger library panic Raw: [1600677634:227954][16124:140717079221488], file:WiredTiger.wt, WT_SESSION.checkpoint: __wt_panic, 523: the process must exit and restart: WT_PANIC: WiredTiger library panic
[mongod output] 2020-09-21_11:40:34.227 [onfhir-akka.actor.default-dispatcher-2] DEBUG i.o.a.s.FHIRUpdateService - updating (creating a new version) document in database as it already exists
2020-09-21T11:40:34.228+0300 F -        [WTCheckpointThread] Fatal Assertion 50853 at src\mongo\db\storage\wiredtiger\wiredtiger_util.cpp 401
[mongod output] 2020-09-21T11:40:34.228+0300 F -        [WTCheckpointThread] 
[mongod output] 
[mongod output] ***aborting after fassert() failure
[mongod output] 
[mongod output] 
[mongod output] 2020-09-21T11:40:34.229+0300 F -        [conn5] Fatal Assertion 28559 at src\mongo\db\storage\wiredtiger\wiredtiger_util.cpp 62
[mongod output] 2020-09-21T11:40:34.229+0300 F -        [conn5] 
[mongod output] 
[mongod output] ***aborting after fassert() failure
[mongod output] 
[mongod output] 
[mongod output] 2020-09-21_11:40:34.470 [Thread-14] WARN  o.m.d.connection - Got socket exception on connection [connectionId{localValue:5, serverValue:5}] to localhost:27018. All connections to localhost:27018 will be closed.

2020-09-21_11:41:04.489 [onfhir-akka.actor.default-dispatcher-4] ERROR i.o.s.ErrorHandler$ - Unexpected exception!
com.mongodb.MongoSocketReadException: Exception receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:569)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1200(InternalStreamConnection.java:76)
	at com.mongodb.internal.connection.InternalStreamConnection$5.failed(InternalStreamConnection.java:520)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.failed(AsynchronousChannelStream.java:235)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.failed(AsynchronousChannelStream.java:203)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
	at sun.nio.ch.Invoker.invoke(Invoker.java:185)
	at sun.nio.ch.Invoker.invoke(Invoker.java:297)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.failed(WindowsAsynchronousSocketChannelImpl.java:600)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:399)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The specified network name is no longer available.

	at sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:309)
	at sun.nio.ch.Iocp.access$700(Iocp.java:46)
	... 5 common frames omitted
2020-09-21_11:41:04.490 [onfhir-akka.actor.default-dispatcher-2] DEBUG i.o.a.s.FHIRUpdateService - requesting 'update' for Patient with af4e036eedce9584ea564f8a75c3cdef...
2020-09-21_11:41:21.864 [MaintenanceTimer-1-thread-1] WARN  o.m.d.connection - Exception thrown during connection pool background maintenance task
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:117)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
	at sun.nio.ch.Invoker.invoke(Invoker.java:185)
	at sun.nio.ch.Invoker.invoke(Invoker.java:297)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ConnectTask.failed(WindowsAsynchronousSocketChannelImpl.java:302)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:399)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The remote computer refused the network connection.

	at sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:309)
	at sun.nio.ch.Iocp.access$700(Iocp.java:46)
	... 5 common frames omitted
2020-09-21_11:42:04.497 [onfhir-akka.actor.default-dispatcher-4] ERROR i.o.s.ErrorHandler$ - Unexpected exception!
java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:172)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:170)
	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:108)
	at scala.concurrent.Await$.result(package.scala:142)
	at io.onfhir.api.service.FHIRBatchTransactionService.executeChildInteraction(FHIRBatchTransactionService.scala:124)
	at io.onfhir.api.service.FHIRBatchTransactionService.$anonfun$performBatchRequest$4(FHIRBatchTransactionService.scala:176)
	at io.onfhir.api.service.FHIRBatchTransactionService.$anonfun$performBatchRequest$4$adapted(FHIRBatchTransactionService.scala:173)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at io.onfhir.api.service.FHIRBatchTransactionService.$anonfun$performBatchRequest$1(FHIRBatchTransactionService.scala:173)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2020-09-21_11:42:04.499 [onfhir-akka.actor.default-dispatcher-2] DEBUG i.o.a.s.FHIRUpdateService - requesting 'update' for Patient with 81babdda1eab99919b10506d6299a7fd...
2020-09-21_11:42:21.824 [MaintenanceTimer-1-thread-1] WARN  o.m.d.connection - Exception thrown during connection pool background maintenance task
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:117)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
	at sun.nio.ch.Invoker.invoke(Invoker.java:185)
	at sun.nio.ch.Invoker.invoke(Invoker.java:297)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ConnectTask.failed(WindowsAsynchronousSocketChannelImpl.java:302)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:399)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The remote computer refused the network connection.

	at sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:309)
	at sun.nio.ch.Iocp.access$700(Iocp.java:46)
	... 5 common frames omitted

```

**Comment by sinaci** [comment]
This is a PC spesific problem where the operating system or other applications limit access to the embedded mongo's files.
